displayName: GeoBlock ASN
type: middleware

import: github.com/T0ut4t1s/traefik-geoblock-asn

summary: "Block requests based on country of origin and ASN"

testData:
  silentStartUp: false
  allowLocalRequests: true
  logLocalRequests: false
  logAllowedRequests: false
  logApiRequests: true
  api: "https://get.geojs.io/v1/ip/geo/{ip}.json"
  apiTimeoutMs: 500
  cacheSize: 25
  forceMonthlyUpdate: true
  allowUnknownCountries: false
  unknownCountryApiResponse: "nil"
  countries:
    - GB
    - JP
  allowedASNs:
    - 2856
    - 5378
  blockedASNs: []
  addAsnHeader: false
  allowUnknownAsn: false
